### ISSUE TITLE
WCF 프레임워크에 대한 논의사항

### ISSUE THREAD

**Issue by Kang-Programming** [pyj9293/Prom#2]
WCF의 필요성에 대한 논의사항 입니다.

@nlpoolm : 확인바랍니다.
@Kang-Programming : 올린이.
@pyj9293 : 확인바랍니다.

경로 :
Prom/1. 요구 사항/WCF.txt
Prom/1. 요구사항/WCF 참고자료(SOA를 구현하기 위한 개발 및 적용 방안).pptx

**Comment by pyj9293** [comment]
> @pyj9293 : 확인바랍니다.

@Kang-Programming 중국에 있는 관계로 구글이 안들어가집니다. 직접 이슈에 올려주시기 바랍니다.

**Comment by nlpoolm** [comment]
@Kang-Programming 확인했습니다.
